/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package utilities

import kotlin.test.Test
import kotlin.test.assertFails
import kotlin.test.assertNotNull

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = UtilitiesLibrary()

        assert(classUnderTest.randomCode(10).length == 10)

        assertFails {
            UtilitiesLibrary.Values.Email("notEmail@string@")
        }
        assertNotNull(UtilitiesLibrary.Values.Email("email@string.ru").email)
    }
}
